Get customer
mrojasabregu/customer-service pull request #6
Opened 2021-11-17 20:54 UTC by Antoovar

2021-11-17 21:09 UTC, Yanina-31 approved these changes

2021-11-17 21:09 UTC, Yanina-31 commented on .gitignore
> +/.idea/
.idea cambiarlo

2021-11-17 21:09 UTC, Yanina-31 commented on src/main/java/com/example/customer/customerService/Controller/ControllerCustomer.java
> +    public List<Customer> getCustomer(@RequestParam(name="name") String name, @RequestParam(nae
getCustomers

2021-11-17 21:09 UTC, Yanina-31 commented on src/main/java/com/example/customer/customerService/Repository/CustomerDao.java
> + public List<Customer> findByParams(String name, String lastName, String email, Long phone) {
Long phone ----> cambiarlo a String

2021-11-17 21:09 UTC, Yanina-31 commented on src/main/java/com/example/customer/customerService/Domain/Model/Customer.java
> +    private Long phone;
Long phone ----> cambiarlo a String

2021-11-17 21:09 UTC, Yanina-31 commented on src/main/java/com/example/customer/customerService/Controller/ControllerCustomer.java
> +        serviceCustomer.getCustomers(name, lastName, email, phone);
Long phone ----> cambiarlo a String

2021-11-17 21:09 UTC, Yanina-31 commented on src/main/java/com/example/customer/customerService/Service/Imp/ServiceCustomer.java
> +  public List<Customer> getCustomers(String name,String lastName,String email,long phone){
Long phone ----> cambiarlo a String

2021-11-17 21:11 UTC, germansanz93 requested changes

2021-11-17 21:11 UTC, germansanz93 commented on .gitignore
> +/.idea/
esto es .idea

2021-11-17 21:11 UTC, germansanz93 commented on .idea/customer-service.iml
>  <?xml version="1.0" encoding="UTF-8"?>
esto no va

2021-11-17 21:11 UTC, germansanz93 commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
esto no va

2021-11-17 21:11 UTC, germansanz93 commented on src/main/java/com/example/customer/customerService/Controller/ControllerCustomer.java
> +    public List<Customer> getCustomer(@RequestParam(name="name") String name, @RequestParam(nae
name=last_name

2021-11-17 21:11 UTC, germansanz93 commented on src/main/java/com/example/customer/customerService/Controller/ControllerCustomer.java
> +            ="last_Name") String lastName, @RequestParam(name = "email") String email, @RequestParam(name = "phone") long phone){
phone es string

2021-11-17 21:11 UTC, germansanz93 commented on src/main/java/com/example/customer/customerService/Service/Imp/ServiceCustomer.java
> +  public List<Customer> getCustomers(String name,String lastName,String email,long phone){
Long y no el primitivo long

2021-11-17 21:16 UTC, tinchonp approved these changes

2021-11-18 04:25 UTC, germansanz93 approved these changes
Sos crack!

2021-11-18 04:41 UTC, closed without merging